### PR TITLE
openssl: ia32-generic: disable sse2 instruction set

### PR DESCRIPTION
**Pull request by damianloew**
## Description

- openssl: ia32-generic: disable sse2 instruction set

## Motivation and Context

JIRA: PD-263

Using some ca-certificates (for example `Baltimore_CyberTrust_Root.crt`) by `openssl` causes executing `sse2` instructions that are not supported on Phoenix-RTOS (ia32-generic). As @Maxez said it's not possible to disable it in the processor, so the `no-sse2` option in `openssl` has to be set. It's required for working azure iot sdk (upcoming port).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (ia32-generic qemu).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
please elaborate in commit message why this is needed and maybe add "openssl: ia32:" in commit topic as the change is only for this taget family

**Comment by damianloew** [comment]
> please elaborate in commit message why this is needed and maybe add "openssl: ia32:" in commit topic as the change is only for this taget family
> 
> Edit: comment in the changed config describing why this is needed would also be ok

Thanks, I was describing why it's needed in pr message. I will update commit message too.

**Comment by nalajcie** [comment]
Please write:
 - WHAT You're doing in commit topic
 - WHY You're doing it in commit message (so the "because..." and partially what You've written in this PR should go there)

The PR description is mostly never read again after the PR is mereged... as opposed to git log / git blame which may be very helpful in the future.

Also, I still don't really understand why this is needed. SSE2 is a HW feature, is any special support from OS also needed?

If our OS doesn't support these extensions, we should choose CPU to be emulated (eg. `-cpu pentium3` qemu param should solve SSE2 - which was added in Pentium 4 - but maybe we need to choose older processor?)

**Comment by Maxez** [comment]
@nalajcie OS does need to support SSE instructions (so that #UD exception is not generated, [link](https://wiki.osdev.org/SSE#Adding_support)). We'd also have to save and restore XMM registers at context switch.

Please note that openssl only checks for SSE2 hardware support (via cpuid instruction). It doesn't know if the OS supports it too.

Sidenote:
Running qemu with -cpu pentium3 also solves the problem (cpuid won't report SSE2 support).

**Comment by damianloew** [comment]
> Please write:
> 
> * WHAT You're doing in commit topic
> * WHY You're doing it in commit message (so the "because..." and partially what You've written in this PR should go there)
> 
> The PR description is mostly never read again after the PR is mereged... as opposed to git log / git blame which may be very helpful in the future.
> 
> Also, I still don't really understand why this is needed. SSE2 is a HW feature, is any special support from OS also needed?
> 
> If our OS doesn't support these extensions, we should choose CPU to be emulated (eg. `-cpu pentium3` qemu param should solve SSE2 - which was added in Pentium 4 - but maybe we need to choose older processor?)

You are right, corrected. Please let me know if it's ok now. I am not sure what option is better (specifying core without sse2/disabling sse2 in openssl). I would like to merge it and next eventually think about choosing the specific core for qemu. But I will do what You think is better.

**Comment by nalajcie** [comment]
If we're currently running `qemu` with CPU we're not supporting than we should fix it ASAP :).

I would prefer not to impair openssl functionality as I hope we will add `sse2` support somewhere down the road. 
Please also that the commit description is invalid as it's possible to disable sse2 in qemu. @damianloew can You check if providing the proposed parameters solve Your issue without additional openssl changes?

**Comment by damianloew** [comment]
> 

Yes, I've verified that using qemu script with `-cpu pentium3` instead of this change is sufficient for me.

**Comment by damianloew** [comment]
> If we're currently running `qemu` with CPU we're not supporting than we should fix it ASAP :).
> 
> I would prefer not to impair openssl functionality as I hope we will add `sse2` support somewhere down the road. Please also that the commit description is invalid as it's possible to disable sse2 in qemu. @damianloew can You check if providing the proposed parameters solve Your issue without additional openssl changes?

Yes, I've verified that using qemu script with -cpu pentium3 instead of this change is sufficient for me.

**Pull request closed without merging**
